image: gitpod/workspace-python-3.12

vscode:
  extensions:
    - https://github.com/freeCodeCamp/freecodecamp-dark-vscode-theme/releases/download/v1.0.0/freecodecamp-dark-vscode-theme-1.0.0.vsix

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

tasks:
  - init: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

      nvm install --lts
      nvm use --lts

      npm install
    command: npm run start
